Revert back to using good ol' ssh-agent

diff --git a/roles/bash/files/bash.d/1password b/roles/bash/files/bash.d/1password
--- a/roles/bash/files/bash.d/1password
+++ b/roles/bash/files/bash.d/1password
@@ -5,8 +5,8 @@ function openv() {
   local arg=$1
   local openv_sess_file=${HOME}/.openv-session
 
-  if [[ -z "$arg" || ("$arg" != "up" && "$arg" != "down") ]]; then
-    echo "usage: openv <up | down>"
+  if [[ -z "$arg" || ("$arg" != "up" && "$arg" != "down" && "$arg" != "addkeys") ]]; then
+    echo "usage: openv <up | down | addkeys>"
     return 1
   fi
 
@@ -55,5 +55,33 @@ function openv() {
     rm -rf "$openv_sess_file"
     unset OP_SESSION_my
     unset OP_CONFIG_DIR
+  fi
+
+  if [[ "$arg" == "addkeys" ]]; then
+    # OP_CONFIG_DIR: 1password cli --config location
+    if [[ ! -f "$openv_sess_file" || -z "$OP_SESSION_my" ]]; then
+      echo "1password session not yet established, run \"openv up\" first"
+      return 1
+    fi
+
+    local keys
+    keys=`op get item --vault="Private" "ssh-keys"`
+    if [ "$?" -ne 0 ]; then
+      echo "Failed to get retrieve SSH keys"
+      return 1
+    fi
+
+    for section in $(echo ${keys} | jq -r -c '.details.sections[] | @base64'); do
+      _val() {
+        echo ${section} | base64 --decode | jq -r ${1}
+      }
+      _title=$(_val '.title')
+
+      _privatekey=$(echo ${section} | base64 --decode | jq -r '.fields[] | select(.t == "private") | .v')
+      _publickey=$(echo ${section} | base64 --decode | jq -r '.fields[] | select(.t == "public") | .v')
+      _fp=$(echo -ne "${_publickey}" | ssh-keygen -lf -)
+      echo "Adding key: ${_title} - ${_fp}"
+      echo -ne "${_privatekey}" | ssh-add -
+    done
   fi
 }
