Document & automate the file restoration process

diff --git a/roles/macbook_setup/templates/acd-backup.sh.j2 b/roles/macbook_setup/templates/acd-backup.sh.j2
--- a/roles/macbook_setup/templates/acd-backup.sh.j2
+++ b/roles/macbook_setup/templates/acd-backup.sh.j2
@@ -9,8 +9,8 @@ SYSLOG_TAG="${PROGRAM_NAME}"
 LOCKFILE="${HOME}/tmp/${PROGRAM_NAME}-lockfile.txt"
 RCLONE="/usr/local/bin/rclone"
 RCLONE_FILTERS="${HOME}/.rclone-filters"
-BACKUP_SRC="${HOME}/"
-BACKUP_DEST="amazon:files"
+BACKUP_LOCAL="${HOME}/Dropbox"
+BACKUP_UPSTREAM="s3backup:{{ acd_backups_s3_bucket_name }}/files/Dropbox"
 TIMESTAMP="${HOME}/tmp/backup-timestamp.txt"
 
 info() {
@@ -44,19 +44,37 @@ echo $$ > ${LOCKFILE}
 
 rm -f ${TIMESTAMP}
 
-# Backup all the relevant files
+# Sync all the files locally using the upstream as the source
 ${RCLONE} \
   --filter-from ${RCLONE_FILTERS} \
   --transfers 10 \
   --checkers 10 \
-  --size-only \
-  sync ${BACKUP_SRC} ${BACKUP_DEST} \
+  --update \
+  sync ${BACKUP_UPSTREAM} ${BACKUP_LOCAL} \
   2>&1 | /usr/bin/logger --id \
   --priority 'local3.info' \
   --tag "${SYSLOG_TAG}"
 
 if [ $? -eq 0 ]; then
-  info "Backup finshed successfully"
+  info "Remote to local sync completed successfully"
+else
+  cleanup
+  error "Error completing backup"
+fi
+
+# Sync all the upstream files using the local files as the source
+${RCLONE} \
+  --filter-from ${RCLONE_FILTERS} \
+  --transfers 10 \
+  --checkers 10 \
+  --update \
+  sync ${BACKUP_LOCAL} ${BACKUP_UPSTREAM} \
+  2>&1 | /usr/bin/logger --id \
+  --priority 'local3.info' \
+  --tag "${SYSLOG_TAG}"
+
+if [ $? -eq 0 ]; then
+  info "Local to remote sync completed successfully"
   echo `date` > ${TIMESTAMP}
 else
   warn "Error completing backup"
